# Generated by Django 2.1.4 on 2018-12-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burd326',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=1, max_length=1)),
                ('is_available', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=3)),
                ('next_date_available', models.DateField()),
                ('number_of_bedrooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=1)),
                ('rent_per_month', models.PositiveSmallIntegerField(default=0)),
                ('features', models.TextField()),
                ('applicances', models.TextField()),
            ],
        ),
    ]
