# Generated by Django 2.1.4 on 2019-05-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='first_name',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='last_name',
            new_name='last',
        ),
    ]
