# Generated by Django 2.1.4 on 2018-12-19 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burd326',
            name='next_date_available',
        ),
    ]
