# Generated by Django 2.1.4 on 2019-05-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190514_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='name',
        ),
        migrations.AddField(
            model_name='email',
            name='first_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='email',
            name='last_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(default='', max_length=32),
        ),
    ]
