# Generated by Django 2.1.4 on 2018-12-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_burd328_earl44_earl46_earl48_orange229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burd328',
            name='apartment_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='earl44',
            name='apartment_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='earl46',
            name='apartment_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='earl48',
            name='apartment_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='orange229',
            name='apartment_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=1, max_length=1),
        ),
    ]
