# Generated by Django 2.1.4 on 2018-12-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181223_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='burd326',
            old_name='applicances',
            new_name='appliances',
        ),
        migrations.RenameField(
            model_name='burd328',
            old_name='applicances',
            new_name='appliances',
        ),
        migrations.RenameField(
            model_name='earl44',
            old_name='applicances',
            new_name='appliances',
        ),
        migrations.RenameField(
            model_name='earl46',
            old_name='applicances',
            new_name='appliances',
        ),
        migrations.RenameField(
            model_name='earl48',
            old_name='applicances',
            new_name='appliances',
        ),
        migrations.RenameField(
            model_name='orange229',
            old_name='applicances',
            new_name='appliances',
        ),
    ]
