# Generated by Django 2.1.4 on 2019-01-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181223_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='burd326',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='burd328',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='earl44',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='earl46',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='earl48',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='orange229',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
