# Generated by Django 2.1.4 on 2019-01-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190101_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burd326',
            name='notes',
            field=models.TextField(default='', null=True),
        ),
    ]
