# Generated by Django 2.1.4 on 2019-01-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190101_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burd326',
            name='appliances',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='burd326',
            name='features',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='burd328',
            name='appliances',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='burd328',
            name='features',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='burd328',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='earl44',
            name='appliances',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='earl44',
            name='features',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='earl44',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='earl46',
            name='appliances',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='earl46',
            name='features',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='earl46',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='earl48',
            name='appliances',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='earl48',
            name='features',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='earl48',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='orange229',
            name='appliances',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='orange229',
            name='features',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='orange229',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
